CREATE ROLE ODMSAnalysis AUTHORIZATION dbo;
EXEC sp_addrolemember 'ODMSAnalysis', 'INTERNAL\R867489';

CREATE SCHEMA Analysis AUTHORIZATION ODMSAnalysis;

GRANT CREATE TABLE, CREATE PROCEDURE, CREATE FUNCTION, CREATE VIEW TO ODMSAnalysis;